### ISSUE TITLE
All Sounds Muted

### ISSUE THREAD

**Issue by DotBotCarlos** [henkelmax/sound-physics-remastered#158]
**Bug description**
All audio in the game is not working and seems to be disabled as seen in the log.

**Steps to reproduce the issue**
1. Install the Most Recent Version of the Mod
2. Play the Game
3. Wait For Game to Load
4. Listen for Sounds

**Expected behavior**
To hear the game's sound

**Log files**
https://gist.github.com/DotBotCarlos/e3702a4c9f2af1071b2d0b9a3f6d5c95

**Versions**
- Minecraft 1.20.1
- Fabric 0.14.24
- Sound Physics Remastered 1.2.1

**Other mods**
None. Tested with only Sound Physics

**Comment by Dragonfly-Totem** [comment]
Same issue here; However I _did_ notice that if I actively go to my Windows audio volume, and just.. Click on it -- You know, to initiate the "ping" noise for Windows itself, it then suddenly detects the audio in Minecraft and stops throwing error logs.

Not sure why that's the case, but there's some additional data for you.

**Comment by Pseudoentropy** [comment]
I'm having this issue with water specifically. I noticed it first when boating in the ocean and then when killing squid underwater.

**Comment by henkelmax** [comment]
> https://gist.github.com/DotBotCarlos/e3702a4c9f2af1071b2d0b9a3f6d5c95

This seems to be a general Minecraft issue.

**Comment by FarIntegral** [comment]
Sound Initialization Issue - Mod Requires "Active Audio Output"
Just wanted to share a discovery for anyone struggling with Sound Physics Remastered not playing any sound, and seeing errors like:
"Error starting SoundSystem; Turning off all sounds & music"  
"Failed to get OpenAL attributes"
In the Minecraft logs when running the Sound Physics Remastered mod.

After some testing, I realized the mod doesn't properly initialize unless an active audio output device is already producing sound at the moment Minecraft launches.

This is especially relevant for USB and wireless headsets (like the SteelSeries Arctis series), where Windows tends to power down the output channel until audio is requested -> which then causes OpenAL to fail on initialization, since the mod doesn't activate the output beforehand.

Workaround and test to see if you have this problem:
Start a sound (e.g. a song in Spotify, YouTube, or even a system volume test ping) before launching Minecraft, and keep it running until Minecraft is fully loaded.
I personally kept Spotify open and playing until the game was in the main menu, which guaranteed the mod detected an active device.

As soon as the device is awake and playing something, OpenAL initializes correctly, and the mod functions perfectly throughout the whole session.
Note: This explains why it “randomly works” sometimes- the mod passively waits for a valid output device but doesn’t try to activate or ping it itself. Even whilst Minecraft is running, the mod waits for an output, so as soon as you activate some sound through your headset by the system, the mod can then detect it and starts running smoothly. 

It would be awesome if future versions included a small silent audio ping during startup to trigger device activation, if they don't already do! Until then, this workaround was reliable for these issues.

Hope this helps others who were as confused as I was at first~
