### ISSUE TITLE
Optifine incompatible with mod

### ISSUE THREAD

**Issue by fuzzypicklz** [henkelmax/sound-physics-remastered#46]
**Bug description**
When attempting to boot minecraft with optifine and this mod, it crashes and gives an error.

**Steps to reproduce the issue**
1. install mod
2. install optifine
3. attempt to boot with both in mod folder
4. cry in agony as you cannot run shaders and this beautiful mod at the same time

**Expected behavior**
I would think that these 2 mods would be compatible, but it seems like they aren't...

**Versions**
- Minecraft version
- Forge/Fabric version
- Mod version

**Other mods**
optifine, 3d skin layers (should not affect in any way)
[crash-2022-06-29_13.13.06-client.txt](https://github.com/henkelmax/sound-physics-remastered/files/9014745/crash-2022-06-29_13.13.06-client.txt)

**Comment by fuzzypicklz** [comment]
It might be that this is an issue with optifine... I looked at the crash report, and all the errors seemed to be from optifine. But, I've never seen a mod that is incompatible with optifine...

**Comment by fuzzypicklz** [comment]
Also, there's a good chance that I could be doing something very wrong, have only tested this in 1.19.

**Comment by henkelmax** [comment]
We generally won't fix issues with optifine, since its not possible to look into their code. They are also very ignorant about issues with other mods. They generally almost never solve any bug reports regarding mod compatibility. There are a lot of mods that have the same features as optifine. Please consider using these. For example use iris for shaders.
