### ISSUE TITLE
[Question] Do you want author rights for curseforge project?

### ISSUE THREAD

**Issue by vlad2305m** [henkelmax/sound-physics-remastered#6]
Hello! I see you have forked my project and done some amazing things to it. Do you want to publish it on CurseForge on my project? (For the sake of Forge players)

**Comment by henkelmax** [comment]
Hey,
I already have a CurseForge project for this: https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered

I didn't want to ask you if you want to merge these changes, since I changed the whole configuration structure of the mod. It would basically break existing configuration presets.

**Comment by vlad2305m** [comment]
I am ok with merging the changes since I would have needed to change everything in 1.18 anyway, but I don't like forge, so I can only leave it to you. I feel it is not right to split people into 2 different projects since it slows down the promotion of both. So if you find a way to put your project on my page(eg. as alpha v2), I am happy to give you all the rights and credit. Moreover, alpha projects are invisible, so feel free to come over to my page as an author and add to description as you need.
Hope this isn't too annoying of me )

**Comment by henkelmax** [comment]
If you want, you can merge my changes into your project, but I won't maintain half a project if it would only be Forge. I changed this project into a multi loader setup, so the core code for Forge and Fabric is basically the same.
This project is also only thought for the use with Simple Voice Chat, since your implementation was too slow handling the voice chat audio. I don't intend to steal your userbase. It is just an optimized variant, for the use with voicechat.
